In [38]:
import pandas as pd
import numpy as  np

In [39]:
a=np.array([1,2,3,4,5])
np.fromfunction(lambda i,j:pow(a[j],i),(5,2),dtype=int)

array([[ 1,  1],
       [ 1,  2],
       [ 1,  4],
       [ 1,  8],
       [ 1, 16]], dtype=int32)

In [40]:
x = np.vander(a,3)
x

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [41]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [42]:
arr.size

13

In [43]:
def movavg(a,n):
    return(np.convolve(a,np.ones(n),'valid')/n)

In [44]:
movavg(arr,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])